# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJhCGBqFG-5ortpMMf5S4rw-L5kMh22_
"""

# ==============================
# Task 5 - Data Analysis on CSV
# ==============================

import pandas as pd
import matplotlib.pyplot as plt

# Load CSV file
df = pd.read_csv("/content/sample_data/sales.csv")

print("===== FIRST 5 ROWS =====")
print(df.head())

print("\n===== SHAPE OF DATASET =====")
print(df.shape)

print("\n===== COLUMN INFO =====")
print(df.info())

print("\n===== STATISTICAL SUMMARY =====")
print(df.describe())

print("\n===== MISSING VALUES =====")
print(df.isnull().sum())

# Group by Product
product_sales = df.groupby("Product")["Sales"].sum()
print("\n===== TOTAL SALES BY PRODUCT =====")
print(product_sales)

# Group by Region
region_sales = df.groupby("Region")["Sales"].sum()
print("\n===== TOTAL SALES BY REGION =====")
print(region_sales)

# Filter example
high_sales = df[df["Sales"] > 5000]
print("\n===== SALES GREATER THAN 5000 =====")
print(high_sales.head())

# Plot - Sales by Product
plt.figure()
product_sales.plot(kind="bar")
plt.title("Total Sales by Product")
plt.xlabel("Product")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Plot - Sales by Region
plt.figure()
region_sales.plot(kind="bar")
plt.title("Total Sales by Region")
plt.xlabel("Region")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()